### ISSUE TITLE
Intraday data

### ISSUE THREAD

**Issue by MislavSag** [tonytrevisan/fmpcloudr#2]
Hi,

I have just discovered FMP cloud data and this package. Could you please provide more info on 2 questions:

1. How long to the past the intraday data go? I am asking for paid accounts.
2. Is it possible to retrieve split and dividend-adjusted intraday data?
3. Are you satisfied with the data. It's hard to know for somebody new if data is trustworthy. For example, I was using IB till today and they have problems with split adjustments.

Best

**Comment by altanalytics** [comment]
Hi,

Thanks for reaching out. This package is only a wrapper around FMP api, not the source itself. I think you should direct these questions at them FMP. They have excellent customer support on their site fmpcloud.io.

Dividend and split adjusted data is available. From my personal experience, the data is good but I have found some issues. Everyone struggles with splits. You can verify the data against tiingo as well. 

Best,
Exploring Finance

**Comment by MislavSag** [comment]
I have asked FMP the same questions yesterday. I thought you have payed account and maybe know the answers. I will wait for few days to answer.

**Comment by MislavSag** [comment]
I have paid for an individual subscription for 1 month. The answer to all the above questions is NO. So, I have spent 20$ on nothing. I don't understand how useful is to have intraday data for few months into the past. And for fundamental data there is simfin+ which is great.
