### ISSUE TITLE
ttm values

### ISSUE THREAD

**Issue by MislavSag** [tonytrevisan/fmpcloudr#3]
Hi 

IN docs, there is a possibility to use ttm values. For example, key-metrics-ttm, but I can't find it in the package (key option is available).

**Comment by altanalytics** [comment]
Set trailingTwelve = TRUE such as: fmpc_financial_metrics('AAPL',metric = 'key', trailingTwelve = TRUE)

**Comment by MislavSag** [comment]
For me, this only returns last tmm observations (no history), but I have calculated them by myself using rollsum.

Maybe more important question. Why FMP use the date of the report as the date in financial ratios, key ratios etc.
The statements are visible to the public on a filled date (or accepted date?), so for me, it is logical to set the filled date as the date column and not the date of the report. Or at least to show all 3 dates (accepted, filled, date of the report).

How did you solve this problem?

**Comment by altanalytics** [comment]
I have not worked with this data set previously so have not had to solve for this. You can reach out to FMP directly on their site.  They are very responsive via their chat on https://fmpcloud.io/
