### ISSUE TITLE
startDate argument doesnt work

### ISSUE THREAD

**Issue by MislavSag** [tonytrevisan/fmpcloudr#4]
If I try this code:

wmi_intraday <- fmpc_price_intraday('WM', freq = '1hour', startDate = "2009-07-20")

It returns the most recent data and not the data from "2009-07-20".

**Comment by altanalytics** [comment]
This is a limitation from FMP. Try setting the end date. They appear to limit hourly data to 500 ish rows.
fmpc_price_intraday('WM', freq = '1hour', startDate = "2009-07-20", endDate = '2009-11-01').  Please note the data starts at 2009-08-05.
You can see this in the demo as well: https://fmpcloud.io/api/v3/historical-chart/1hour/AAPL?from=2008-03-12&to=2014-03-12&apikey=demo

**Comment by MislavSag** [comment]
Even if I set start and end date, the function returns most recent data. This code:
```
wmi_intraday <- fmpc_price_intraday('WM', freq = '1hour', startDate = "2009-07-20", endDate = "2009-07-30")
```
returns data from 2021-03-25 to 2021-04-22. Maybe there is no data in the 2009, but why it returns most recent data than? It should null or something?


BTW, there are lots of limitations of FMP, but I have already paid for subscription, so have to use it :(

**Comment by altanalytics** [comment]
run it for September 2009. There is no data prior to Aug 2009 for this ticker. I am pretty sure you can cancel your subscription at any time.

**Comment by MislavSag** [comment]
I know there is no data, but it is weird it returns newest data when there is no data for specified time frame. 

I can cancel, but I have paid one year subscription in advance.
