### ISSUE TITLE
fmpc_security_splits throws error when there's no data to return

### ISSUE THREAD

**Issue by pete0** [tonytrevisan/fmpcloudr#6]
fmpc_security_splits or fmpc_security_dividends now throw an error if the return is empty:

>fmpc_security_splits("DIS")
Error in UseMethod("relocate") : 
no applicable method for 'relocate' applied to an object of class "list"

**Comment by pete0** [comment]
note I found this was a bug in the helper function hlp_symbolHistory() -- the ```is.null``` check no longer works because the data is now returned as an empty list instead of null
Changing ```if (is.null(result$historical)) return(NULL)``` to ```if (!length(result$historical)) return(NULL)``` worked for me

**Comment by altanalytics** [comment]
Thanks for the ti - I fixed it and pushed to Github. I won't push to CRAN unless I make some bigger updates.
